# Generated by Django 6.0.7 on 2026-07-09 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "WebApp",
            "0002_department_organization_user_role_activity_analytics_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=255, unique=True)),
                ("accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="activity",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="activity",
            name="elapsed_time",
            field=models.IntegerField(help_text="Time spent in seconds"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="total_time",
            field=models.IntegerField(help_text="Total time in seconds"),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="WebApp.organization",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="goal_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="WebApp.department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="WebApp.organization",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Organization Admin", "Organization Admin"),
                    ("Technical Admin", "Technical Admin"),
                    ("Managerial Admin", "Managerial Admin"),
                    ("Operational Admin", "Operational Admin"),
                    ("Employee", "Employee"),
                ],
                default="Employee",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analytics",
            unique_together={("user", "category", "date")},
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "date"], name="WebApp_acti_user_id_8ac6f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analytics",
            index=models.Index(
                fields=["user", "date"], name="WebApp_anal_user_id_f49de3_idx"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="WebApp.department"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="WebApp.organization",
            ),
        ),
    ]
