# Generated by Django 6.0.7 on 2026-07-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0003_invitation_alter_activity_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="tab_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="analytics",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="WebApp.organization",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.CharField(default="Employee", max_length=50),
        ),
        migrations.AlterField(
            model_name="activity",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="WebApp.department",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="analytics",
            index=models.Index(
                fields=["organization", "date"], name="WebApp_anal_organiz_f9df97_idx"
            ),
        ),
    ]
