# Generated by Django 6.0.7 on 2026-07-09 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0004_activity_tab_title_analytics_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="activity",
            name="elapsed_time",
            field=models.IntegerField(help_text="Seconds"),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="total_time",
            field=models.IntegerField(help_text="Seconds"),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations",
                to="WebApp.department",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
