# Generated by Django 6.0.7 on 2026-07-10 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0006_remove_invitation_accepted_activity_organization_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name": "Activity", "verbose_name_plural": "Activities"},
        ),
        migrations.AlterModelOptions(
            name="analytics",
            options={"verbose_name": "Analytics", "verbose_name_plural": "Analytics"},
        ),
        migrations.AlterField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
