# Generated by Django 6.0.7 on 2026-07-11 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0007_alter_activity_options_alter_analytics_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tab_opened", "Tab Opened"),
                            ("tab_closed", "Tab Closed"),
                            ("tab_switched", "Tab Switched"),
                            ("tab_active", "Tab Active"),
                            ("url_changed", "URL Changed"),
                            ("heartbeat", "Heartbeat"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tab_id", models.IntegerField()),
                ("url", models.URLField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="WebApp_acti_user_id_8ac6f7_idx",
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="WebApp_acti_organiz_0edcc1_idx",
        ),
        migrations.AlterModelOptions(
            name="analytics",
            options={},
        ),
        migrations.AddField(
            model_name="activitylog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="WebApp.organization",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="activity",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="user",
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["organization", "date"], name="WebApp_acti_organiz_a8dabe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "date"], name="WebApp_acti_user_id_6c678c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["tab_id"], name="WebApp_acti_tab_id_a48efe_idx"),
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
