# Generated by Django 6.0.7 on 2026-07-11 07:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0008_activitylog_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="activitylog",
            name="WebApp_acti_tab_id_a48efe_idx",
        ),
        migrations.RemoveIndex(
            model_name="analytics",
            name="WebApp_anal_user_id_f49de3_idx",
        ),
        migrations.RemoveIndex(
            model_name="analytics",
            name="WebApp_anal_organiz_f9df97_idx",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="active_duration",
            field=models.IntegerField(default=0, help_text="Focused time seconds"),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="session_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="duration",
            field=models.IntegerField(
                default=0, help_text="Total tab duration seconds"
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tab_opened", "Tab Opened"),
                    ("tab_closed", "Tab Closed"),
                    ("tab_active", "Tab Active"),
                    ("tab_switched", "Tab Switched"),
                    ("url_changed", "URL Changed"),
                    ("heartbeat", "Heartbeat"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to="WebApp.organization",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="tab_id",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics",
                to="WebApp.organization",
            ),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="total_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["session_id"], name="WebApp_acti_session_732ad4_idx"
            ),
        ),
    ]
