# Generated by Django 6.0.7 on 2026-07-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0009_remove_activitylog_webapp_acti_tab_id_a48efe_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="activitylog",
            name="WebApp_acti_organiz_a8dabe_idx",
        ),
        migrations.RemoveIndex(
            model_name="activitylog",
            name="WebApp_acti_user_id_6c678c_idx",
        ),
        migrations.RemoveIndex(
            model_name="activitylog",
            name="WebApp_acti_session_732ad4_idx",
        ),
        migrations.RenameField(
            model_name="activitylog",
            old_name="date",
            new_name="activity_date",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="active_duration",
            field=models.IntegerField(default=0, help_text="Actual focused seconds"),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="duration",
            field=models.IntegerField(default=0, help_text="Total elapsed seconds"),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "activity_date"], name="WebApp_acti_user_id_422f2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["organization", "activity_date"],
                name="WebApp_acti_organiz_1ebf12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["tab_id", "activity_date"], name="WebApp_acti_tab_id_474eaf_idx"
            ),
        ),
    ]
